In [1]:
import open3d as o3d
import numpy as np
import torch

def visualize_point_cloud(data):
    """
    Visualizes a point cloud using Open3D. Supports N*3 and N*6 point clouds,
    and accepts both NumPy arrays and PyTorch tensors.

    :param data: A NumPy array or PyTorch tensor of shape (N, 3) or (N, 6).
                 For (N, 3), it represents the (x, y, z) coordinates of the points.
                 For (N, 6), it represents the (x, y, z, r, g, b) coordinates and colors of the points.
    """
    if isinstance(data, torch.Tensor):
        data = data.cpu().numpy()

    if data.shape[1] not in [3, 6]:
        raise ValueError("The input data must have shape (N, 3) or (N, 6).")

    point_cloud = o3d.geometry.PointCloud()
    point_cloud.points = o3d.utility.Vector3dVector(data[:, :3])

    if data.shape[1] == 6:
        point_cloud.colors = o3d.utility.Vector3dVector(data[:, 3:])
    
    coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1, origin=[0, 0, 0])
    origin_marker = o3d.geometry.TriangleMesh.create_sphere(radius=0.02)
    origin_marker.paint_uniform_color([1, 0, 0])  # Red color for clear visibility
    origin_marker.translate([0, 0, 0])  # It is already at (0,0,0), this line is optional
    o3d.visualization.draw_geometries([point_cloud, coordinate_frame, origin_marker])

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
import open3d as o3d
def read_pcs_from_ply(path):
    pcd = o3d.io.read_point_cloud(path)
    return np.array(pcd.points), np.array(pcd.colors)

In [3]:
path = "tabletop_objects.pcd"

points,colors = read_pcs_from_ply(path)
print(points)
print(points.shape)


[[-5.5432403e-01 -2.0770936e+00  3.5411119e-04]
 [-5.4505324e-01 -2.0769169e+00  4.9513578e-04]
 [-5.3583294e-01 -2.0769172e+00  4.9495697e-04]
 ...
 [ 2.4733700e-02 -1.4842072e+00  1.0856376e+00]
 [ 3.5682250e-02 -1.4858286e+00  1.0850313e+00]
 [ 4.4689715e-02 -1.4885249e+00  1.0845079e+00]]
(11184, 3)


In [4]:
#visualize_point_cloud(points)

In [16]:
nx, ny = (3, 2)
print(nx)
x = np.linspace(0, 1, nx)
print(x)
y = np.linspace(0, 1, ny)
print(y)

xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)



3
[0.  0.5 1. ]
[0. 1.]
[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]


In [10]:
import open3d as o3d
import numpy as np
import torch

def fill_objects(points, grid_resolution=100):
    """
    given the surface point cloud of the objects, fill the internal point clouds(padding). 
    Based on the normal vector and the original plane at (x,y,0). fill all the points between the surface and the original plane
    



grid_x [[-1.3329346  -1.31025473 -1.28757486 ...  0.86701297  0.88969284
   0.91237271]
 [-1.3329346  -1.31025473 -1.28757486 ...  0.86701297  0.88969284
   0.91237271]
 [-1.3329346  -1.31025473 -1.28757486 ...  0.86701297  0.88969284
   0.91237271]
 ...
 [-1.3329346  -1.31025473 -1.28757486 ...  0.86701297  0.88969284
   0.91237271]
 [-1.3329346  -1.31025473 -1.28757486 ...  0.86701297  0.88969284
   0.91237271]
 [-1.3329346  -1.31025473 -1.28757486 ...  0.86701297  0.88969284
   0.91237271]]
grid_x (100, 100)
grid_z [[1.0891948 1.0891948 1.0891948 ... 1.0891948 1.0891948 1.0891948]
 [1.0891948 1.0891948 1.0891948 ... 1.0891948 1.0891948 1.0891948]
 [1.0891948 1.0891948 1.0891948 ... 1.0891948 1.0891948 1.0891948]
 ...
 [1.0891948 1.0891948 1.0891948 ... 1.0891948 1.0891948 1.0891948]
 [1.0891948 1.0891948 1.0891948 ... 1.0891948 1.0891948 1.0891948]
 [1.0891948 1.0891948 1.0891948 ... 1.0891948 1.0891948 1.0891948]]
grid_z (100, 100)


In [ ]:
# 可视化合并后的点云
visualize_point_cloud(combined_data)


In [ ]:
"""The very original way to visualize the point cloud""""


import open3d as o3d
import numpy as np

# Load your point cloud (adjust the path as needed)
pcd = o3d.io.read_point_cloud("tabletop_objects.pcd")

print(pcd)
# Create a coordinate frame (axes of length 0.1)
coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1, origin=[0, 0, 0])

# Create a small sphere to mark the origin (0,0,0)
origin_marker = o3d.geometry.TriangleMesh.create_sphere(radius=0.02)
origin_marker.paint_uniform_color([1, 0, 0])  # Red color for clear visibility
origin_marker.translate([0, 0, 0])  # It is already at (0,0,0), this line is optional



PointCloud with 11184 points.


TriangleMesh with 762 points and 1520 triangles.

In [3]:
# Visualize the point cloud along with the coordinate frame and origin marker
o3d.visualization.draw_geometries([pcd, coordinate_frame, origin_marker])
